### ISSUE TITLE
Artifactory Maven not working after update

### ISSUE THREAD

**Issue by chrizzo84** [jfrog/artifactory-vsts-extension#105] opened 2019-11-05 15:14 UTC
Since last update our Maven Artifactory Builds are not running.
Out of my view it is skipping the step without any error.
Pls check.

**Comment by dirien** [comment] 2019-11-05 15:18
Here a screen.
<img width="1075" alt="Ohne Titel" src="https://user-images.githubusercontent.com/38325136/68220330-dbb34d00-ffe7-11e9-8394-cd942fa9f18a.png">

**Comment by RobiNino** [comment] 2019-11-05 16:32
Hi @chrizzo84 and @dirien , thanks for reporting this issue.
We are currently unable to reproduce. 

Can you please provide some more details about your build?
Are you both running on hosted Ubuntu agent? With what goals and options?
Thanks

**Comment by dirien** [comment] 2019-11-06 06:37
Hosted ubuntu agent

##[debug]mavenPOMFile=/home/vsts/work/1/s/pom.xml
##[debug]goals=clean test
##[debug]options=--batch-mode
##[debug]collectBuildInfo=false
##[debug]JFROG_CLI_JCENTER_REMOTE_SERVER=undefined
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]Build Succeeded.
##[debug]includeEnvVars=false

**Comment by RobiNino** [comment] 2019-11-06 09:05
Thanks @dirien. It seems that a bug related to the 'collectBuildInfo' checkbox was introduced  in version 1.7.0.
We will release a fix in the next few hours.

As a workaround, please set collectBuildInfo=true until we release the new version. 
Would love to hear that indeed solves the problem.
Thanks

**Comment by dirien** [comment] 2019-11-06 09:11
I think the error is in here:

```
function appendBuildFlagsToCliCommand(cliCommand) {
    if (tl.getBoolInput("collectBuildInfo")) {
        // Construct the build-info collection flags.
        let buildName = tl.getInput('buildName', true);
        let buildNumber = tl.getInput('buildNumber', true);
        return cliJoin(cliCommand, "--build-name=" + quote(buildName), "--build-number=" + quote(buildNumber));
    }
}
```

I checked out your code and try to build a fix version for our projects. There are complete blocked right now...

**Comment by dirien** [comment] 2019-11-06 09:25
there is a else missig!

I run the test locally

`function appendBuildFlagsToCliCommand(cliCommand) {
    if (tl.getBoolInput("collectBuildInfo")) {
        console.log("appendBuildFlagsToCliCommand "+cliCommand);
        tl.debug("appendBuildFlagsToCliCommand "+cliCommand);
        // Construct the build-info collection flags.
        let buildName = tl.getInput('buildName', true);
        let buildNumber = tl.getInput('buildNumber', true);
        return cliJoin(cliCommand, "--build-name=" + quote(buildName), "--build-number=" + quote(buildNumber));
    } else {
        return cliCommand;
    }
}`

**Comment by dirien** [comment] 2019-11-06 09:29
i created a pull request @RobiNino

**Comment by eyalbe4** [comment] 2019-11-06 09:44
Thanks so much for the fix @dirien!
Actually, @RobiNino managed to reproduce the issue and came up with a similar code fix.
We're working to release this fix as we speak.
In addition, we think that with the *Collect build-info* checkbox checked, the issue should not happen. If you get a chance to try this and confirm that it solves the issue, before we release the patch, that could really help.
Thank you!

**Comment by dirien** [comment] 2019-11-06 09:49
Hi @eyalbe4 , we can confirm it works with checked. 

Kudos ti @RobiNino 

Unfortunatly we can not rollout this as a workaround because people yous pipline as code and dont wont to create PR etc for this and the rollback... 

So we eagerly wait for your final fix :)

BTW: nice to see how collaboration in action plays nice!

**Comment by eyalbe4** [comment] 2019-11-06 10:06
Absolutely @dirien!
Looking forward to future feedback and collaboration :)

**Comment by RobiNino** [comment] 2019-11-06 10:48
Hi @chrizzo84 and @dirien , version 1.7.3 is now released and includes a fix for this issue.
Thank you for your patience and help.

**Comment by dirien** [comment] 2019-11-06 11:12
Yeah! Works like a charm! Cheers!  Good work @RobiNino and @eyalbe4 !

<img width="1064" alt="Ohne Titel 2" src="https://user-images.githubusercontent.com/38325136/68293610-98f88000-008e-11ea-8666-590de7cc3531.png">

**Comment by eyalbe4** [comment] 2019-11-06 13:25
Great @dirien!
@chrizzo84 - please let us know if all works well on your end as well.
Thanks

**Comment by dirien** [comment] 2019-11-06 13:32
@eyalbe4 : @chrizzo84 sits next to me! 

Everything works fine for him to. You can close the ticket :)

**Comment by chrizzo84** [comment] 2019-11-06 14:15
Seems that everything is working fine again. Thx.

**Closed** 2019-11-06 14:15 UTC
