### ISSUE TITLE
[Error] error parsing regexp: invalid escape sequence: `\1`

### ISSUE THREAD

**Issue by neolutin** [jfrog/artifactory-vsts-extension#29] opened 2018-09-07 14:13 UTC
When I try to use the 'Artifactory NuGet push' I ran in the error below (similar to the issue #5 ).
If I modify the Path to NuGet package(s) to publish from '$(Build.ArtifactStagingDirectory)/*.nupkg' to the complete name of the package (i.e. $(Build.ArtifactStagingDirectory)/Module.$(FullVersion).nupkg) everything is ok.

Here are the logs:
2018-09-07T10:14:26.2810656Z ##[section]Starting: Artifactory NuGet push
2018-09-07T10:14:26.2819160Z ==============================================================================
2018-09-07T10:14:26.2820002Z Task         : Artifactory Nuget
2018-09-07T10:14:26.2820679Z Description  : Restore and push NuGet packages from and to Artifactory while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
2018-09-07T10:14:26.2821367Z Version      : 1.1.0
2018-09-07T10:14:26.2821728Z Author       : JFrog
2018-09-07T10:14:26.2822222Z Help         : [More Information](https://www.jfrog.com/confluence/display/RTF/NuGet+Repositories)
2018-09-07T10:14:26.2822783Z ==============================================================================
2018-09-07T10:14:27.3066415Z Running jfrog-cli from D:\vsts\agents\1\_work\_jfrog\current\jfrog.exe.
2018-09-07T10:14:42.3783116Z JFrog CLI version: 1.19.1
2018-09-07T10:14:42.4310653Z Collecting environment variables...
2018-09-07T10:14:46.4534661Z [Info] Collecting environment variables...
2018-09-07T10:14:46.4601282Z [Info] Collected environment variables for Scripts/20180907.8.
2018-09-07T10:14:46.5471874Z [Error] error parsing regexp: invalid escape sequence: `\1`
2018-09-07T10:14:46.5473961Z {
2018-09-07T10:14:46.5474986Z [Error] Upload finished with errors. Please review the logs
2018-09-07T10:14:46.5475423Z   "status": "failure",
2018-09-07T10:14:46.5478208Z   "totals": {
2018-09-07T10:14:46.5478926Z     "success": 0,
2018-09-07T10:14:46.5479637Z     "failure": 0
2018-09-07T10:14:46.5480215Z   }
2018-09-07T10:14:46.5480859Z }
2018-09-07T10:14:46.5568056Z ##[error]Error: Command failed: D:\vsts\agents\1\_work\_jfrog\current\jfrog.exe rt u D:\vsts\agents\1\_work\13\a\*.nupkg repository/Scripts/20180907.8/Module/ --build-name="Scripts" --build-number="20180907.8" --url="http://artifactory.net/artifactory" --user=*** --password=***
2018-09-07T10:14:46.5572186Z Error: Command failed: D:\vsts\agents\1\_work\_jfrog\current\jfrog.exe rt u D:\vsts\agents\1\_work\13\a\*.nupkg repository/Scripts/20180907.8/Module/ --build-name="Scripts" --build-number="20180907.8" --url="http://artifactory.net/artifactory" --user=*** --password=***
2018-09-07T10:14:46.5734030Z ##[section]Finishing: Artifactory NuGet push

The backslashes of the Windows path on the server seems to not be correctly escaped.
Can you please check?

**Comment by yahavi** [comment] 2018-09-09 08:14
Thanks for reporting this issue, @neolutin.
We are looking into it.

**Comment by dnperfors** [comment] 2018-09-11 08:38
I have indeed the same issue, even with the default value of `**/*.nupkg`. Hopefully the PR of @yahavi will be pushed and released soon, because this is kind of a show stopper for us...

**Comment by eyalbe4** [comment] 2018-09-11 11:55
@dnperfors,
We'd like to release a patch with the fix by the end of the week.

**Comment by eyalbe4** [comment] 2018-09-12 15:32
@neolutin and @dnperfors,
@yahavi's PR has been merged (thanks @yahavi!) and version 1.1.1 has been released.
Please let us know if the new release resolves the issue for you.

**Comment by dnperfors** [comment] 2018-09-13 07:59
@eyalbe4 yes I can confirm that it is working for me, thank you.

**Comment by eyalbe4** [comment] 2018-09-13 08:29
Happy to hear this 😄

**Closed by eyalbe4** 2018-09-13 08:29 UTC

**Comment by neolutin** [comment] 2018-09-13 09:12
@eyalbe4 Ok for me too.
Thanks a lot
